### ISSUE TITLE
elastic apm module can not send data to elastic apm dashboard

### ISSUE THREAD

**Issue by amribrahim** [shabananavas/elastic_apm#32]
Hello, 
kindly  i install the module and configure the 
application name 
server url 
token 
and make apm agent active and save but not data send to apm module 
i used apm server version 7.3.2
so any help

**Comment by shabananavas** [comment]
Please post on d.org so any answers will help others as well. Btw, first thing, check your error logs.

**Comment by amribrahim** [comment]
okey will post it again in d.org but you mean application error log
here us the logs 

----------------------------------------------------------------------------------------
[Wed Aug 12 08:48:35.501733 2020] [php7:notice] [pid 1603] [client 196.158.143.42:61756] TypeError: Argument 1 passed to PhilKra\\Agent::getTransaction() must be of the type string, null given, called in /var/www/html/fikra/modules/contrib/elastic_apm/src/EventSubscriber/RequestSubscriber.php on line 221 in /var/www/html/fikra/vendor/philkra/elastic-apm-php-agent/src/Agent.php on line 175 #0 /var/www/html/fikra/modules/contrib/elastic_apm/src/EventSubscriber/RequestSubscriber.php(221): PhilKra\\Agent->getTransaction(NULL)\n#1 [internal function]: Drupal\\elastic_apm\\EventSubscriber\\RequestSubscriber->onTerminateRequest(Object(Symfony\\Component\\HttpKernel\\Event\\PostResponseEvent), 'kernel.terminat...', Object(Drupal\\Component\\EventDispatcher\\ContainerAwareEventDispatcher))\n#2 /var/www/html/fikra/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php(111): call_user_func(Array, Object(Symfony\\Component\\HttpKernel\\Event\\PostResponseEvent), 'kernel.terminat...', Object(Drupal\\Component\\EventDispatcher\\ContainerAwareEventDispatcher))\n#3 /var/www/html/fikra/vendor/symfony/http-kernel/HttpKernel.php(88): Drupal\\Component\\EventDispatcher\\ContainerAwareEventDispatcher->dispatch('kernel.terminat...', Object(Symfony\\Component\\HttpKernel\\Event\\PostResponseEvent))\n#4 /var/www/html/fikra/vendor/stack/builder/src/Stack/StackedHttpKernel.php(32): Symfony\\Component\\HttpKernel\\HttpKernel->terminate(Object(Symfony\\Component\\HttpFoundation\\Request), Object(Drupal\\Core\\Render\\HtmlResponse))\n#5 /var/www/html/fikra/core/lib/Drupal/Core/DrupalKernel.php(671): Stack\\StackedHttpKernel->terminate(Object(Symfony\\Component\\HttpFoundation\\Request), Object(Drupal\\Core\\Render\\HtmlResponse))\n#6 /var/www/html/fikra/index.php(22): Drupal\\Core\\DrupalKernel->terminate(Object(Symfony\\Component\\HttpFoundation\\Request), Object(Drupal\\Core\\Render\\HtmlResponse))\n#7 {main}, referer: http://fikra-test.monshaat.sa/admin/config/development/elastic-apm/rum
-----------------------------------------------------------------------------------------------------------------------
